<?php

$filters = array();

foreach ($this->filters as $filter) {
    $entry = new \StdClass;
    $entry->tag   = $filter->tag;
    $entry->title = $this->translate($filter->title);
    $entry->options = array();
    foreach ($filter->options as $option) {
        $oEntry = new \StdClass;
        $oEntry->text  = $this->translate($option->text);
        $oEntry->value = $option->value;
        $entry->options[] = $oEntry;
    }
    $filters[] = $entry;
}

echo json_encode($filters);
