<?php
// setting the controller and action name as title segments:
$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle()->append(
    '(' . $request->getActionName() . '/' . $request->getControllerName() . ')'
);

$this->headTitle()->prepend('Tribal Wars Filter');
$this->headTitle()->setSeparator(' :: ');


$this->headLink()->appendStylesheet('/layouts/colour/style.css');

$this->headMeta()
    ->appendName('description', 'website description')
    ->appendName('keywords', 'website keywords, website keywords')
    //->setCharset('UTF-8') <-- Doesn't work so lets use httpEquiv
    ->appendHttpEquiv('content-type', 'text/html; charset=windows-1252');
    
$news = <<<EOT
        <h4>New Website Launched</h4>
        <h5>January 1st, 2010</h5>
        <p>2010 sees the redesign of our website. Take a look around and let us know what you think.<br /><a href="#">Read more</a></p>
        <p></p>
        <h4>New Website Launched</h4>
        <h5>January 1st, 2010</h5>
        <p>2010 sees the redesign of our website. Take a look around and let us know what you think.<br /><a href="#">Read more</a></p>
EOT;
$links = <<<EOT
        <ul>
          <li><a href="#">link 1</a></li>
          <li><a href="#">link 2</a></li>
          <li><a href="#">link 3</a></li>
          <li><a href="#">link 4</a></li>
        </ul>
EOT;
$form = <<<EOT
    <form method="post" action="#" id="search_form">
      <p>
        <input class="search" type="text" name="search_field" value="Enter keywords....." />
        <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="/layouts/colour/search.png" alt="Search" title="Search" />
      </p>
    </form>
EOT;
$this->sidebar()->append($news,  'Latest news');
$this->sidebar()->append($links, 'Useful links');
$this->sidebar()->append($form,  'Search');
?>
<!DOCTYPE HTML>
<html>

<head>
  <?php echo $this->headTitle() ?>
  <?php echo $this->headMeta() ?>
  <?php echo $this->headLink() ?>
  <?php echo $this->headScript() ?>
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="index.html">colour<span class="logo_colour">blue</span></a></h1>
          <h2>Simple. Contemporary. Website Template.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li class="selected"><a href="index.html">Home</a></li>
          <li><a href="examples.html">Examples</a></li>
          <li><a href="page.html">A Page</a></li>
          <li><a href="another_page.html">Another Page</a></li>
          <li><a href="contact.html">Contact Us</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <?php echo $this->sidebar() ?>
      <div id="content">
        <!-- insert the page content here -->
        <?php echo $this->layout()->content; ?>
      </div>
    </div>
    <div id="content_footer"></div>
    <div id="footer">
      Copyright &copy; colour_blue | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">design from HTML5webtemplates.co.uk</a>
    </div>
  </div>
  <?php echo $this->googleAnalytics(); ?>
</body>
</html>
