<?php
$this->headTitle()->append('Tribal Wars Filter');
$this->headTitle()->setSeparator(' :: ');


$this->headLink()->appendStylesheet($this->baseUrl('layouts/twf/style.css'));
$this->headLink()->appendStylesheet($this->baseUrl('layouts/twf-fb/style-overwrite.css'));
$this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=UnifrakturCook:700');

$this->headMeta()
    ->appendName('description', 'website description')
    ->appendName('keywords', 'website keywords, website keywords')
    //->setCharset('UTF-8') <-- Doesn't work so lets use httpEquiv
    ->appendHttpEquiv('content-type', 'text/html; charset=utf-8');

//$this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js');
$this->headScript()->prependFile($this->baseUrl('scripts/view.js'));
$this->headScript()->prependFile($this->baseUrl('scripts/jquery.min.js'));
?>
<!DOCTYPE HTML>
<html>

    <head>
        <?php echo $this->headTitle() ?>
          <?php echo $this->headMeta() ?>
          <?php echo $this->headLink() ?>
          <?php echo $this->headScript() ?>
    </head>    
    
    <body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=268340919940956";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
        <div class="golden-bar"></div>
        <div id="header">
            <h1>Tribal Wars Filter</h1>
        </div>
        <div id="container">
            <div class="golden-bar"></div>
            <div id="real-content">
                <div id="sidebar">
                    <?php echo $this->sidebar() ?>
                </div>
                <div id="content">
                <fb:intl desc="Asking whether user wants to give a book to someone">
  Give <fb:name uid="4800348" useyou="false"/> a copy of "{book-title}"?
  <fb:intl-token name="book-title">
      Catcher In the Rye
  </fb:intl-token>
</fb:intl>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
        <div id="footer">

            Copyright &copy; Tribal Wars Filter | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a><br>
            Tribal Wars © 2003 - 2011 InnoGames GmbH
        </div>
        <?php echo $this->googleAnalytics(); ?>
    </body>
    
</html>
