<?php
    $this->message = $this->translate($this->message);
    $this->headTitle()->prepend($this->message);
?>

<h1><?php echo $this->translate('An error occurred'); ?></h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>

<h3><?php echo $this->translate('Exception information:'); ?></h3>
<p>
  <b><?php echo $this->translate('Message:'); ?></b> <?php echo $this->exception->getMessage() ?>
</p>

<h3><?php echo $this->translate('Stack trace:'); ?></h3>
<pre><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3><?php echo $this->translate('Request parameters:'); ?></h3>
<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
</pre>

<?php endif ?>
